#!/usr/bin/env python3
# Created By: Atri Sarker
# Date: March 3, 2025
# This module holds the function for generating the code,
# given the parameters from the main file
from datetime import datetime
import math


def volume_formula(type: str):
    # length represents base length
    # height represents height
    full_formula = ""
    base = f"base_area"
    if type == "Prism":
        full_formula = f"({base}) * height"
    elif type == "Pyramid":
        full_formula = f"({base}) * (height/3)"

    return full_formula


def surface_area_formula(side_amount: int, type: str):
    # length represents base length
    # height represents height
    # n represents the side amount
    n = side_amount
    full_formula = ""
    base = "base_area"
    if type == "Prism":
        full_formula = f"2*({base}) + (length*{n}*height)"
    elif type == "Pyramid":
        slant_formula = (
            f"(height**2 + ( (length/2)*{(math.tan((0.5 - 1/n)*math.pi))} )**2)**0.5"
        )
        full_formula = f"({base}) + (length*{n*0.5}*({slant_formula}))"

    return full_formula


# Creates the code
def get_code(side_amount: int, type: str, unitType: str):
    # Get Date
    today = datetime.today()
    month = [
        "Jan",
        "Feb",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December",
    ][today.month - 1]
    # n represents the side amount
    n = side_amount
    res = f"""#!/usr/bin/env python3
# Generated by https://github.com/ICS3U-Programming-AtriS/Assign-02-Python
# Date: {month} {today.day}, {today.year}
# Calculator for the Volume and Surface Area of a
# Regular {n}-sided polygonal {type}

# Function that makes sure input is a positive number
def valid_input(prompt:str):
  while True:
    try:
        print("\\033[0m", end="") # WHITE TEXT
        res = float(input(prompt))
        if res > 0:
            return res
        else:
            print("\\033[0;31m", end="") # RED TEXT
            print("Value must be a positive number")
    except ValueError:
        print("\\033[0;31m", end="") # RED TEXT
        print("Value must be a positive number")

def main():
    # Welcome Message
    print("\\033[0;34m", end="") # BLUE TEXT
    print("This program calculates the Volume and Surface area")
    print("of a Regular {n}-sided polygonal {type}")
    # Input
    # Get side length (length of the base sides)
    length = valid_input("Enter base length({unitType}): ")
    # Get height
    height = valid_input("Enter height({unitType}): ")

    # Process
    # Calculate the Area of the Base [Used for simplifying calculations]
    base_area = {n} * (1/4) * (length**2) * {math.tan((0.5 - 1/n)*math.pi)}
    # Calculate the Volume
    volume = {volume_formula(type)}
    # Calculate the Surface Area
    surface_area = {surface_area_formula(n, type)}

    # Output
    print("\\033[0;32m", end="") # GREEN TEXT
    print("The Volume is " + str(round(volume,2)) + "{unitType}\u00b3")
    print("The Surface Area is " + str(round(surface_area,2)) + "{unitType}\u00b2")

if __name__ == "__main__":
    main()

"""

    return res
